-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_target_profiles
-- Purpose: Reusable target profile (prefix, schema, tracing, auditing,
--          instance type, DB/APEX version) the generator uses to produce
--          code that compiles on the developer instance.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_target_profiles_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_target_profiles (
    target_profile_id             number generated by default on null as identity (start with 1) primary key not null
  , name                          varchar2(200 char) not null
  , object_prefix                 varchar2(30 char) not null
  , target_schema                 varchar2(128 char)
  , trace_mode_code               varchar2(20 char) default 'apex_debug' not null
  , audit_enabled_yn              varchar2(1 char) default 'Y' not null
  , instance_type_code            varchar2(20 char) default 'apex' not null
  , db_version                    varchar2(30 char)
  , apex_version                  varchar2(30 char)
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_target_profiles_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_target_profiles_trace_mode check (trace_mode_code in ('none', 'apex_debug', 'logger'))
  , constraint ck_arw_target_profiles_audit_enabled_yn check (audit_enabled_yn in ('Y', 'N'))
  , constraint ck_arw_target_profiles_instance_type check (instance_type_code in ('apex', 'autonomous'))
  , constraint uk_target_profiles_name unique (name)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_target_profiles_active on arw_target_profiles (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_target_profiles is ''Reusable target profile: prefix, schema, tracing, auditing, instance type, DB/APEX version.''';
  execute immediate 'comment on column arw_target_profiles.target_profile_id is ''Unique identifier of the target profile.''';
  execute immediate 'comment on column arw_target_profiles.name is ''Display name of the target profile.''';
  execute immediate 'comment on column arw_target_profiles.object_prefix is ''Object prefix to use in the generated code (e.g. arw).''';
  execute immediate 'comment on column arw_target_profiles.target_schema is ''Target schema; null when the generator assumes the current schema (see IMPLEMENTATION.md section 14).''';
  execute immediate 'comment on column arw_target_profiles.trace_mode_code is ''Tracing framework to emit: none, apex_debug or logger.''';
  execute immediate 'comment on column arw_target_profiles.audit_enabled_yn is ''Y when the generated code should include execution auditing.''';
  execute immediate 'comment on column arw_target_profiles.instance_type_code is ''Target instance type: apex or autonomous.''';
  execute immediate 'comment on column arw_target_profiles.db_version is ''Target database version (e.g. 19c, 23ai).''';
  execute immediate 'comment on column arw_target_profiles.apex_version is ''Target APEX version (e.g. 24.1, 26.1).''';
  execute immediate 'comment on column arw_target_profiles.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
