-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_executions
-- Purpose: History of real calls: request sent (headers redacted), observed
--          response, status and elapsed time. Every discovery sample
--          (arw_response_samples) comes from a row in this table.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_executions_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.
--
-- Note: request_headers/response_headers must already be redacted by
-- arw_exec_api before the insert -- see ddl-conventions.md / security.md and
-- the "Authorization header in history" pitfall in IMPLEMENTATION.md
-- section 12. response_body_clob/response_body_blob are mutually exclusive,
-- selected by response_is_binary_yn (see IMPLEMENTATION.md section 12,
-- "Binary responses").


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_executions (
    execution_id                  number generated by default on null as identity (start with 1) primary key not null
  , endpoint_id                   number not null
  , environment_id                number not null
  , request_status_code           varchar2(20 char) not null
  , http_status_code              number
  , elapsed_ms                    number
  , request_headers               clob
  , request_body                  clob
  , response_headers              clob
  , response_body_clob            clob
  , response_body_blob            blob
  , response_is_binary_yn         varchar2(1 char) default 'N' not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_executions_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_executions_request_status check (request_status_code in ('success', 'error', 'timeout'))
  , constraint ck_arw_executions_response_is_binary_yn check (response_is_binary_yn in ('Y', 'N'))
  , constraint fk_executions_endpoints foreign key (endpoint_id) references arw_endpoints (endpoint_id)
  , constraint fk_executions_environments foreign key (environment_id) references arw_environments (environment_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_executions_active on arw_executions (active_yn);
create index idx_arw_executions_endpoint on arw_executions (endpoint_id);
create index idx_arw_executions_environment on arw_executions (environment_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_executions is ''History of real calls: request (headers redacted), response, status and elapsed_ms.''';
  execute immediate 'comment on column arw_executions.execution_id is ''Unique identifier of the execution.''';
  execute immediate 'comment on column arw_executions.endpoint_id is ''Endpoint that was executed.''';
  execute immediate 'comment on column arw_executions.environment_id is ''Environment this call was executed against.''';
  execute immediate 'comment on column arw_executions.request_status_code is ''Outcome of the call itself (success, error, timeout), independent of the returned HTTP status.''';
  execute immediate 'comment on column arw_executions.http_status_code is ''HTTP status code returned; null when there was no response (timeout/network error).''';
  execute immediate 'comment on column arw_executions.elapsed_ms is ''Elapsed time of the call, in milliseconds.''';
  execute immediate 'comment on column arw_executions.request_headers is ''Headers sent, with sensitive values already redacted before being stored.''';
  execute immediate 'comment on column arw_executions.request_body is ''Body sent with the request.''';
  execute immediate 'comment on column arw_executions.response_headers is ''Headers returned by the service.''';
  execute immediate 'comment on column arw_executions.response_body_clob is ''Response body when response_is_binary_yn = N.''';
  execute immediate 'comment on column arw_executions.response_body_blob is ''Response body when response_is_binary_yn = Y (binary or larger than 32k).''';
  execute immediate 'comment on column arw_executions.response_is_binary_yn is ''Y when the response was captured as a blob instead of a clob.''';
  execute immediate 'comment on column arw_executions.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
