-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_environments
-- Purpose: Execution environment (dev/qa/prod) within a collection; defines
--          the base_url its endpoints run against.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_environments_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_environments (
    environment_id               number generated by default on null as identity (start with 1) primary key not null
  , collection_id                number not null
  , name                         varchar2(200 char) not null
  , base_url                     varchar2(1000 char) not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_environments_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_environments_collections foreign key (collection_id) references arw_collections (collection_id)
  , constraint uk_environments_name unique (collection_id, name)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_environments_active on arw_environments (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_environments is ''Environment (dev/qa/prod) within a collection; defines the base_url used by its endpoints.''';
  execute immediate 'comment on column arw_environments.environment_id is ''Unique identifier of the environment.''';
  execute immediate 'comment on column arw_environments.collection_id is ''Collection this environment belongs to.''';
  execute immediate 'comment on column arw_environments.name is ''Display name of the environment (e.g. Dev, QA, Prod).''';
  execute immediate 'comment on column arw_environments.base_url is ''Base URL that endpoints in this collection resolve against.''';
  execute immediate 'comment on column arw_environments.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
