-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_endpoints
-- Purpose: The configured request (method, path, timeout, runtime/engine).
--          Does not carry environment_id: the environment is chosen at
--          execution time (see arw_executions.environment_id) so the same
--          endpoint can run against dev/qa/prod, Postman-style.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_endpoints_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_endpoints (
    endpoint_id                   number generated by default on null as identity (start with 1) primary key not null
  , collection_id                 number not null
  , credential_id                 number
  , name                          varchar2(200 char) not null
  , http_method                   varchar2(10 char) not null
  , url_path                      varchar2(1000 char) not null
  , timeout_secs                  number default 30 not null
  , runtime_target_code           varchar2(20 char) default 'apex' not null
  , engine_code                   varchar2(30 char) default 'apex_web_service' not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                   coalesce(
                                     sys_context('APEX$SESSION','app_user')
                                   , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                   , sys_context('userenv','session_user')
                                   )
                                   not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_endpoints_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_endpoints_http_method check (http_method in (
      'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'
    ))
  , constraint ck_arw_endpoints_runtime_target check (runtime_target_code in ('apex', 'job', 'autonomous'))
  , constraint ck_arw_endpoints_engine check (engine_code in (
      'apex_web_service', 'apex_web_service_b', 'utl_http', 'dbms_cloud_send_request'
    ))
  , constraint fk_endpoints_collections foreign key (collection_id) references arw_collections (collection_id)
  , constraint fk_endpoints_credentials foreign key (credential_id) references arw_credentials (credential_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_endpoints_active on arw_endpoints (active_yn);
create index idx_arw_endpoints_collection on arw_endpoints (collection_id);
create index idx_arw_endpoints_credential on arw_endpoints (credential_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_endpoints is ''The configured request: method, path, timeout, target runtime and invocation engine.''';
  execute immediate 'comment on column arw_endpoints.endpoint_id is ''Unique identifier of the endpoint.''';
  execute immediate 'comment on column arw_endpoints.collection_id is ''Collection this endpoint belongs to.''';
  execute immediate 'comment on column arw_endpoints.credential_id is ''Credential used to authenticate the call; null when the endpoint requires no auth.''';
  execute immediate 'comment on column arw_endpoints.name is ''Display name of the endpoint.''';
  execute immediate 'comment on column arw_endpoints.http_method is ''HTTP verb of the request.''';
  execute immediate 'comment on column arw_endpoints.url_path is ''Path relative to the active environment base_url; supports {{var}} tokens.''';
  execute immediate 'comment on column arw_endpoints.timeout_secs is ''Call timeout, in seconds.''';
  execute immediate 'comment on column arw_endpoints.runtime_target_code is ''Target runtime for the generated code: apex (live session), job (scheduler, no APEX session) or autonomous.''';
  execute immediate 'comment on column arw_endpoints.engine_code is ''Invocation engine: apex_web_service, apex_web_service_b (blob), utl_http or dbms_cloud_send_request.''';
  execute immediate 'comment on column arw_endpoints.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
