-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_env_variables
-- Purpose: {{...}} variables of an environment, substituted into url_path,
--          headers, params and body_template at execution time.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_env_variables_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_env_variables (
    variable_id                  number generated by default on null as identity (start with 1) primary key not null
  , environment_id               number not null
  , var_name                     varchar2(200 char) not null
  , var_value                    varchar2(4000 char)
  , is_secret_yn                 varchar2(1 char) default 'N' not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_env_variables_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_env_variables_is_secret_yn check (is_secret_yn in ('Y', 'N'))
  , constraint fk_env_variables_environments foreign key (environment_id) references arw_environments (environment_id)
  , constraint uk_env_variables_name unique (environment_id, var_name)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_env_variables_active on arw_env_variables (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_env_variables is ''{{...}} variables of an environment, substituted into endpoints at execution time.''';
  execute immediate 'comment on column arw_env_variables.variable_id is ''Unique identifier of the variable.''';
  execute immediate 'comment on column arw_env_variables.environment_id is ''Environment this variable belongs to.''';
  execute immediate 'comment on column arw_env_variables.var_name is ''Variable name, referenced as {{var_name}}.''';
  execute immediate 'comment on column arw_env_variables.var_value is ''Variable value. Redact in UI/logs when is_secret_yn = Y.''';
  execute immediate 'comment on column arw_env_variables.is_secret_yn is ''Y when the value is sensitive and must be hidden on screen/history.''';
  execute immediate 'comment on column arw_env_variables.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
