-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_data_profiles
-- Purpose: Data profile derived from a response sample -- rowSelector and
--          observed format, consolidated by arw_discover_api.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_data_profiles_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_data_profiles (
    data_profile_id               number generated by default on null as identity (start with 1) primary key not null
  , response_sample_id            number not null
  , name                          varchar2(200 char) not null
  , row_selector                  varchar2(500 char)
  , format_code                   varchar2(10 char) default 'json' not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_data_profiles_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_data_profiles_format check (format_code in ('json'))
  , constraint fk_data_profiles_response_samples foreign key (response_sample_id) references arw_response_samples (sample_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_data_profiles_active on arw_data_profiles (active_yn);
create index idx_arw_data_profiles_sample on arw_data_profiles (response_sample_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_data_profiles is ''Data profile derived from a response sample: rowSelector and observed format.''';
  execute immediate 'comment on column arw_data_profiles.data_profile_id is ''Unique identifier of the profile.''';
  execute immediate 'comment on column arw_data_profiles.response_sample_id is ''Response sample this profile was derived from.''';
  execute immediate 'comment on column arw_data_profiles.name is ''Name of the profile (e.g. suggested table/dataProfile name).''';
  execute immediate 'comment on column arw_data_profiles.row_selector is ''Path to the array of rows within the response (e.g. items).''';
  execute immediate 'comment on column arw_data_profiles.format_code is ''Format of the observed response; only json for now.''';
  execute immediate 'comment on column arw_data_profiles.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
