-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_endpoint_params
-- Purpose: path / query / form parameters of an endpoint.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_endpoint_params_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_endpoint_params (
    param_id                     number generated by default on null as identity (start with 1) primary key not null
  , endpoint_id                  number not null
  , param_kind_code              varchar2(10 char) not null
  , param_name                   varchar2(200 char) not null
  , param_value                  varchar2(4000 char)
  , data_type_code               varchar2(20 char) default 'varchar2' not null
  , is_required_yn               varchar2(1 char) default 'N' not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_endpoint_params_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_endpoint_params_kind check (param_kind_code in ('path', 'query', 'form'))
  , constraint ck_arw_endpoint_params_data_type check (data_type_code in ('varchar2', 'number', 'date', 'boolean'))
  , constraint ck_arw_endpoint_params_is_required_yn check (is_required_yn in ('Y', 'N'))
  , constraint fk_endpoint_params_endpoints foreign key (endpoint_id) references arw_endpoints (endpoint_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_endpoint_params_active on arw_endpoint_params (active_yn);
create index idx_arw_endpoint_params_endpoint on arw_endpoint_params (endpoint_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_endpoint_params is ''path / query / form parameters of an endpoint.''';
  execute immediate 'comment on column arw_endpoint_params.param_id is ''Unique identifier of the parameter.''';
  execute immediate 'comment on column arw_endpoint_params.endpoint_id is ''Endpoint this parameter belongs to.''';
  execute immediate 'comment on column arw_endpoint_params.param_kind_code is ''Parameter kind: path, query or form.''';
  execute immediate 'comment on column arw_endpoint_params.param_name is ''Parameter name.''';
  execute immediate 'comment on column arw_endpoint_params.param_value is ''Default/sample value for the parameter; supports {{var}} tokens.''';
  execute immediate 'comment on column arw_endpoint_params.data_type_code is ''Parameter data type: varchar2, number, date or boolean.''';
  execute immediate 'comment on column arw_endpoint_params.is_required_yn is ''Y when the parameter is required to execute the endpoint.''';
  execute immediate 'comment on column arw_endpoint_params.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
