-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_response_samples
-- Purpose: Marks that an execution (arw_executions) counts as a discovery
--          sample. Does not duplicate request/response/status/elapsed_ms --
--          that data is read via execution_id, since every sample comes
--          from a real execution already recorded in the history.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_response_samples_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_response_samples (
    sample_id                     number generated by default on null as identity (start with 1) primary key not null
  , endpoint_id                   number not null
  , execution_id                  number not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_response_samples_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_response_samples_endpoints foreign key (endpoint_id) references arw_endpoints (endpoint_id)
  , constraint fk_response_samples_executions foreign key (execution_id) references arw_executions (execution_id)
  , constraint uk_response_samples_execution unique (execution_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_response_samples_active on arw_response_samples (active_yn);
create index idx_arw_response_samples_endpoint on arw_response_samples (endpoint_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_response_samples is ''Marks an execution as a discovery sample; request/response are read via execution_id.''';
  execute immediate 'comment on column arw_response_samples.sample_id is ''Unique identifier of the sample.''';
  execute immediate 'comment on column arw_response_samples.endpoint_id is ''Endpoint this sample belongs to.''';
  execute immediate 'comment on column arw_response_samples.execution_id is ''Execution this sample comes from (unique per execution).''';
  execute immediate 'comment on column arw_response_samples.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
