-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_profile_columns
-- Purpose: One row per field discovered in a data profile. Feeds the
--          json_table, the APEXlang dataProfileColumn and the generated
--          package record type. Nested hierarchy is modeled via
--          parent_column_id (self-reference).
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_profile_columns_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.
--
-- Note: this is the most important table in the system (see
-- IMPLEMENTATION.md section 3.2 and implementation_plan.md section 3,
-- discovery block). Everything else derives from it: json_table, the
-- APEXlang dataProfileColumn, the record type.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_profile_columns (
    column_id                     number generated by default on null as identity (start with 1) primary key not null
  , data_profile_id               number not null
  , parent_column_id              number
  , column_name                   varchar2(200 char) not null
  , path_expression               varchar2(500 char) not null
  , sequence_num                  number
  , data_type_code                varchar2(30 char) not null
  , source_data_type              varchar2(30 char)
  , format_mask                   varchar2(100 char)
  , max_observed_length           number
  , is_nullable_yn                varchar2(1 char) default 'Y' not null
  , is_primary_key_yn             varchar2(1 char) default 'N' not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_profile_columns_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_profile_columns_data_type check (data_type_code in (
      'varchar2', 'number', 'date', 'timestamp_with_time_zone', 'boolean', 'clob'
    ))
  , constraint ck_arw_profile_columns_is_nullable_yn check (is_nullable_yn in ('Y', 'N'))
  , constraint ck_arw_profile_columns_is_primary_key_yn check (is_primary_key_yn in ('Y', 'N'))
  , constraint fk_profile_columns_data_profiles foreign key (data_profile_id) references arw_data_profiles (data_profile_id)
  , constraint fk_profile_columns_parent foreign key (parent_column_id) references arw_profile_columns (column_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_profile_columns_active on arw_profile_columns (active_yn);
create index idx_arw_profile_columns_profile on arw_profile_columns (data_profile_id);
create index idx_arw_profile_columns_parent on arw_profile_columns (parent_column_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_profile_columns is ''One row per field discovered in a data profile; nested hierarchy via parent_column_id.''';
  execute immediate 'comment on column arw_profile_columns.column_id is ''Unique identifier of the discovered field.''';
  execute immediate 'comment on column arw_profile_columns.data_profile_id is ''Profile this field belongs to.''';
  execute immediate 'comment on column arw_profile_columns.parent_column_id is ''Parent field, used to model nested arrays/objects.''';
  execute immediate 'comment on column arw_profile_columns.column_name is ''Proposed column name (e.g. ORDER_ID).''';
  execute immediate 'comment on column arw_profile_columns.path_expression is ''JSON path of the field within the row (e.g. id, created).''';
  execute immediate 'comment on column arw_profile_columns.sequence_num is ''Order of the field within the profile.''';
  execute immediate 'comment on column arw_profile_columns.data_type_code is ''Proposed data type for the field.''';
  execute immediate 'comment on column arw_profile_columns.source_data_type is ''JSON type observed in the sample (string, number, boolean, object, array, null).''';
  execute immediate 'comment on column arw_profile_columns.format_mask is ''Proposed format mask (e.g. for timestamps).''';
  execute immediate 'comment on column arw_profile_columns.max_observed_length is ''Maximum length observed across the accumulated samples.''';
  execute immediate 'comment on column arw_profile_columns.is_nullable_yn is ''Y when the field is missing or null in at least one observed sample.''';
  execute immediate 'comment on column arw_profile_columns.is_primary_key_yn is ''Y when this field is proposed as a primary key (e.g. id, *_id, code, uuid).''';
  execute immediate 'comment on column arw_profile_columns.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
