-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_credentials
-- Purpose: Reusable authentication metadata (never the secret itself). The
--          actual secret lives in the native APEX credential store
--          (apex_credential); this table only references its static_id.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_credentials_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.
--
-- Note: global catalog with no inbound FK -- referenced from
-- arw_endpoints.credential_id (auth per endpoint, see implementation_plan.md
-- section 3). Does not model 'none': an endpoint with no authentication
-- simply leaves credential_id null.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_credentials (
    credential_id                 number generated by default on null as identity (start with 1) primary key not null
  , name                          varchar2(200 char) not null
  , auth_type_code                varchar2(30 char) not null
  , apex_credential_static_id     varchar2(255 char)
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                   coalesce(
                                     sys_context('APEX$SESSION','app_user')
                                   , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                   , sys_context('userenv','session_user')
                                   )
                                   not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_credentials_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_credentials_auth_type check (auth_type_code in (
      'basic', 'bearer', 'api_key_header', 'api_key_query'
    , 'oauth2_client_credentials', 'oauth2_password'
    , 'oci', 'mtls', 'sigv4', 'jwt_signed'
    ))
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_credentials_active on arw_credentials (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_credentials is ''Reusable authentication metadata; the secret lives in apex_credential, this table only references its static_id.''';
  execute immediate 'comment on column arw_credentials.credential_id is ''Unique identifier of the credential.''';
  execute immediate 'comment on column arw_credentials.name is ''Display name of the credential (e.g. Acme Bearer Token).''';
  execute immediate 'comment on column arw_credentials.auth_type_code is ''Authentication type: basic, bearer, api_key_header, api_key_query, oauth2_client_credentials, oauth2_password, oci, mtls, sigv4, jwt_signed.''';
  execute immediate 'comment on column arw_credentials.apex_credential_static_id is ''Static ID of the matching apex_credential entry; the secret itself is never stored here.''';
  execute immediate 'comment on column arw_credentials.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
