-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_collections
-- Purpose: Postman-collection-style grouping. Hierarchical root for
--          environments and endpoints; can be nested via parent_collection_id.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_collections_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_collections (
    collection_id                number generated by default on null as identity (start with 1) primary key not null
  , name                         varchar2(200 char) not null
  , description                  varchar2(500 char)
  , parent_collection_id         number
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_collections_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_collections_parent foreign key (parent_collection_id) references arw_collections (collection_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_collections_active on arw_collections (active_yn);
create index idx_arw_collections_parent on arw_collections (parent_collection_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_collections is ''Postman-collection-style grouping; groups environments and endpoints, nestable via parent_collection_id.''';
  execute immediate 'comment on column arw_collections.collection_id is ''Unique identifier of the collection.''';
  execute immediate 'comment on column arw_collections.name is ''Display name of the collection.''';
  execute immediate 'comment on column arw_collections.description is ''Free-text description of the collection.''';
  execute immediate 'comment on column arw_collections.parent_collection_id is ''Parent collection, used to organize collections into nested folders.''';
  execute immediate 'comment on column arw_collections.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
