-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_endpoint_headers
-- Purpose: Request headers configured for an endpoint.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_endpoint_headers_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_endpoint_headers (
    header_id                    number generated by default on null as identity (start with 1) primary key not null
  , endpoint_id                  number not null
  , header_name                  varchar2(200 char) not null
  , header_value                 varchar2(4000 char)
  , is_sensitive_yn              varchar2(1 char) default 'N' not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_endpoint_headers_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_endpoint_headers_is_sensitive_yn check (is_sensitive_yn in ('Y', 'N'))
  , constraint fk_endpoint_headers_endpoints foreign key (endpoint_id) references arw_endpoints (endpoint_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_endpoint_headers_active on arw_endpoint_headers (active_yn);
create index idx_arw_endpoint_headers_endpoint on arw_endpoint_headers (endpoint_id);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_endpoint_headers is ''Request headers configured for an endpoint.''';
  execute immediate 'comment on column arw_endpoint_headers.header_id is ''Unique identifier of the header.''';
  execute immediate 'comment on column arw_endpoint_headers.endpoint_id is ''Endpoint this header belongs to.''';
  execute immediate 'comment on column arw_endpoint_headers.header_name is ''HTTP header name (e.g. Authorization, Content-Type).''';
  execute immediate 'comment on column arw_endpoint_headers.header_value is ''Header value; supports {{var}} tokens.''';
  execute immediate 'comment on column arw_endpoint_headers.is_sensitive_yn is ''Y when the value must be redacted in the execution history (e.g. Authorization).''';
  execute immediate 'comment on column arw_endpoint_headers.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
