-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_code_templates
-- Purpose: Versioned generator fragments, by section and variant -- the
--          hybrid generation engine described in IMPLEMENTATION.md
--          section 5. Adding a new auth/engine variant is a matter of
--          inserting rows, not recompiling.
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_code_templates_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.
--
-- Note: variant_code intentionally has no check constraint -- it is the
-- value of whichever axis applies (basic, bearer, job, etc.) and its
-- catalog must be able to grow by inserting rows, without altering the
-- table (see IMPLEMENTATION.md section 5).


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_code_templates (
    code_template_id              number generated by default on null as identity (start with 1) primary key not null
  , template_type_code            varchar2(30 char) not null
  , variant_code                  varchar2(30 char) not null
  , section_code                  varchar2(30 char) not null
  , sequence_num                  number default 10 not null
  , template_body                 clob not null
  , active_yn                     varchar2(1 char) default 'Y' not null
  , created_by                    varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                    timestamp with local time zone default localtimestamp not null
  , last_updated_by               varchar2(60 char)
  , last_updated_on               timestamp with local time zone
  , constraint ck_arw_code_templates_active_yn check (active_yn in ('Y', 'N'))
  , constraint ck_arw_code_templates_type check (template_type_code in (
      'plsql_block', 'plsql_package', 'json_table'
    , 'apexlang_rds', 'apexlang_install_script', 'apexlang_ai_tool', 'curl'
    ))
  , constraint ck_arw_code_templates_section check (section_code in (
      'declaration', 'headers', 'auth', 'invocation', 'status', 'parsing', 'example'
    ))
  , constraint uk_code_templates_section unique (template_type_code, variant_code, section_code, sequence_num)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_code_templates_active on arw_code_templates (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_code_templates is ''Versioned generator fragments, by section and variant (hybrid engine).''';
  execute immediate 'comment on column arw_code_templates.code_template_id is ''Unique identifier of the fragment.''';
  execute immediate 'comment on column arw_code_templates.template_type_code is ''Output type: plsql_block, plsql_package, json_table, apexlang_rds, apexlang_install_script, apexlang_ai_tool or curl.''';
  execute immediate 'comment on column arw_code_templates.variant_code is ''Value of the axis that applies (e.g. basic, bearer, job); open catalog, grows by inserting rows.''';
  execute immediate 'comment on column arw_code_templates.section_code is ''Assembly pipeline section: declaration, headers, auth, invocation, status, parsing or example.''';
  execute immediate 'comment on column arw_code_templates.sequence_num is ''Assembly order within the same type/variant/section.''';
  execute immediate 'comment on column arw_code_templates.template_body is ''Body of the fragment, with tokens substituted by arw_render_utils.''';
  execute immediate 'comment on column arw_code_templates.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
