-- Implements: .claude/rules/ddl-conventions.md (table naming, audit columns, DDL file structure)
-- =============================================================================
-- Table:   arw_request_bodies
-- Purpose: Request body with {{...}} tokens for an endpoint. An endpoint has
--          at most one body (uk_request_bodies_endpoint).
--
-- @author  Angel Flores (Developer)
-- @created September 09, 2026
-- @ticket  N/A (Phase 0 - initial ARW data model)
-- =============================================================================
-- Note: the audit compound trigger lives in a separate file
-- (triggers/arw_request_bodies_compound_trg.sql) so release/all_triggers.sql
-- picks it up via its triggers/*.sql glob.


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table arw_request_bodies (
    body_id                      number generated by default on null as identity (start with 1) primary key not null
  , endpoint_id                  number not null
  , content_type                 varchar2(200 char) default 'application/json' not null
  , body_template                clob
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_arw_request_bodies_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_request_bodies_endpoints foreign key (endpoint_id) references arw_endpoints (endpoint_id)
  , constraint uk_request_bodies_endpoint unique (endpoint_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_arw_request_bodies_active on arw_request_bodies (active_yn);


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table arw_request_bodies is ''Request body with {{...}} tokens for an endpoint; one body per endpoint.''';
  execute immediate 'comment on column arw_request_bodies.body_id is ''Unique identifier of the body.''';
  execute immediate 'comment on column arw_request_bodies.endpoint_id is ''Endpoint this body belongs to.''';
  execute immediate 'comment on column arw_request_bodies.content_type is ''Content-Type of the body (e.g. application/json).''';
  execute immediate 'comment on column arw_request_bodies.body_template is ''Template of the request body; supports {{var}} tokens.''';
  execute immediate 'comment on column arw_request_bodies.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
